[package]
name = "minesweeper-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.31"
rand = "0.8.5"
eframe = "0.18.0"
threadpool = "1.8.1"